---
title: 'DS 202 - Lab 2: Team'
author: "Connor Carpenter"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
choco <- read.csv("https://xdaiisu.github.io/ds202materials/hwlabs/choco.csv")
```

## 1.) 1852

## 2.) 
```{r}
library(ggplot2)
ggplot(choco, aes(x=Review.Date))+ 
  geom_bar(fill = "blue", colour = "black")+
  theme_bw()+
  theme(axis.title.y = element_text(size = rel(1.4)),
        axis.title.x = element_text(size = rel(1.4)),
        axis.text.x = element_text(size = rel(1.6)),
        axis.text.y = element_text(size = rel(1.6)),
        plot.title = element_text(hjust=0.5, size = rel(2)))+
  labs(x = "Review Date",
       y = "Count",
       title = "Count of Reviews by Year")+ 
  ylim(0, 300)
```

**Reviews vary by year**

## 3.)

```{r}
summary(choco)
```
### USA(787), France(158), Canada(132)
```{r}
##USA
mean(choco[choco$Company.Location == "U.S.A.", ]$Rating)
##FRANCE
mean(choco[choco$Company.Location == "France", ]$Rating)
##CANADA
mean(choco[choco$Company.Location == "Canada", ]$Rating)

```
### Canada has highest, followed by France, and then USA

## 4.)

## 5.)

## 6.)

### I was fairly simple to work together as long as we communicated what parts we were doing to avoid conflicts. Additionally, as long as the file is managed well, git will handle all of the merging like a charm.
